version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: copito
      MYSQL_DATABASE: kartingrm
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./KartingRM/KartingRM
    container_name: backend_app
    environment:
      DB_HOST: mysql
    ports:
      - "8090:8090"
    depends_on:
      - mysql

  frontend:
    build: ./karting-front
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
